version: '2'
services:
  bot:
    build: .
    container_name: "bot"
    environment:
      - FOO=bar
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
